#include "ComponentRegistration.h"

#include "ComponentTypeRegistry.h"
#include "IAssetResolver.h"
#include "MeshRendererComponent.h"

#include "Generated/Runtime/Runtime.reflect.init.h"

namespace Nyx::Engine
{
	namespace
	{
		// A loaded MeshRenderer only knows the paths of its mesh and material; look up the assets.
		void ResolveMeshRendererAssets(MeshRendererComponent& component, ScenePostLoadContext& context)
		{
			if (!context.AssetResolver)
			{
				component.MeshAsset = nullptr;
				component.MaterialAsset = nullptr;
				return;
			}

			component.MeshAsset =
				component.Mesh.IsValid() ? context.AssetResolver->ResolveMesh(component.Mesh.Path) : nullptr;

			component.MaterialAsset =
				component.Material.IsValid() ? context.AssetResolver->ResolveMaterial(component.Material.Path) : nullptr;
		}
	}

	void RegisterComponentTypes()
	{
		// Generated by NyxHeaderTool: registers every NYX_REFLECT(Component) type.
		Nyx::Reflection::Generated::RegisterRuntimeReflectedTypes();

		// Components that need more than their reflected properties after being loaded.
		ComponentTypeRegistry::Get().SetPostLoad<MeshRendererComponent>(&ResolveMeshRendererAssets);
	}
}
